### /authenticate 认证接口
POST http://localhost:9193/authenticate
Content-Type: application/json

{
  "userName": "user1",
  "password": "pwd1"
}


### /aaa 测试GET接口
GET http://localhost:9193/aaa
Authorization: Bearer 11eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyMSIsImV4cCI6MTY2MzUyNjQ2MywiaWF0IjoxNjYzNDkwNDYzfQ.PHqTKHjI4S44DzERZRrphUr_uwiHivhPml9LjnW_Sqg
