### /api/auth/login 认证接口
POST http://localhost:9193/api/auth/login
Content-Type: application/json

{
  "userName": "user1",
  "password": "pwd1"
}

### /api/auth/logout 退出登录接口
POST http://localhost:9193/api/auth/logout





### /test/aaa 测试GET接口
GET http://localhost:9193/test/aaa
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyMSIsImNyZWF0ZWQiOjE2NjM1MDUzNzI4MDIsImV4cCI6MTY2NDExMDE3Mn0.Rwk4t11JcRsKiTNsUoLZsb6NPh3TtYLeGECcUA_9wgl-s9JHVs2X3VJM9JhbW6t0C5YhShGNtft6M6HooQ5OHw
